{% set version = "1.1.57-3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-x13binary
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/x13binary_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/x13binary/x13binary_{{ version }}.tar.gz
  sha256: 6da5c81a937c633b8e66b92831d0ae8ad0d0ea65d15ee0dd4fa8ab3173430ade

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('x13binary')"           # [not win]
    - "\"%R%\" -e \"library('x13binary')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=x13binary
  license: GPL-2.0-or-later
  summary: The US Census Bureau provides a seasonal adjustment program now called 'X-13ARIMA-SEATS' building on both earlier programs called X-11 and X-12 as well as the SEATS program by the Bank of Spain. The US Census Bureau offers both source and binary versions -- which this package integrates for use by other R packages.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - ndmaxar
    - RyanHackney
    - conda-forge/r
    - oblute

# The original CRAN metadata for this package was:

# Package: x13binary
# Type: Package
# Title: Provide the 'x13ashtml' Seasonal Adjustment Binary
# Version: 1.1.39-2
# Date: 2019-05-05
# Author: Dirk Eddelbuettel and Christoph Sax
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Description: The US Census Bureau provides a seasonal adjustment program now called 'X-13ARIMA-SEATS' building on both earlier programs called X-11 and X-12 as well as the SEATS program by the Bank of Spain. The US Census Bureau offers both source and binary versions -- which this package integrates for use by other R packages.
# License: file LICENSE
# Copyright: file inst/COPYRIGHT
# RoxygenNote: 5.0.1
# StagedInstall: no
# NeedsCompilation: no
# Packaged: 2019-05-05 16:49:28.227243 UTC; edd
# License_restricts_use: no
# Repository: CRAN
# Date/Publication: 2019-05-07 08:00:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
